-- Databricks notebook source
CREATE TABLE IF NOT EXISTS genai.rag.shipping_docs ( id BIGINT GENERATED BY DEFAULT AS IDENTITY, file_path STRING, text STRING ) tblproperties (delta.enableChangeDataFeed = true);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS genai.rag.shipping_docs_track (file_name STRING) tblproperties (delta.enableChangeDataFeed = true);

-- COMMAND ----------

--Note that we need to enable Change Data Feed on the table to create the index
CREATE TABLE IF NOT EXISTS genai.rag.shipping_docs_embeddings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  file_path STRING,
  text STRING,
  embedding ARRAY <FLOAT>
) TBLPROPERTIES (delta.enableChangeDataFeed = true);
